spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  application:
    name: turismo-api


  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/turismo_ma?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:turismo}
    password: ${DB_PASSWORD:turismo123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs


jwt:
  secret: 3f8a2b1c9d4e7f6a0b5c8d2e1f3a4b7c9d0e2f5a6b8c1d3e4f7a9b0c2d5e8f1
  expiration: 86400000